[build]
<<<<<<< HEAD
  command = "npm run build"
  publish = "BackPackKidzWebsite"
  functions = "netlify/functions"

[dev]
  publish = "BackPackKidzWebsite"
  functions = "netlify/functions"
=======
  base = "BackPackKidzWebsite"
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"
>>>>>>> 30e6fe9012249aaa5cd7b82acbd2a54a53a17e66
